### ISSUE TITLE
手机端聊天栏太反人类

### ISSUE THREAD

**Issue by switefaster** [M1k0t0/N2-Station#4]
我手机端聊天消息是从下到上堆积的，而且每来一条消息还会给我翻到最下面，希望解决。@Stapxs @M1k0t0

**Comment by switefaster** [comment]
~~随便assign了个ss，那顺便把ck也安排上~~

**Comment by switefaster** [comment]
谁接这个issue记得讲一声

**Comment by Stapxs** [comment]
> 谁接这个issue记得讲一声

我这几天改
不对这是交互的部分
我没参与
还真得让 ck 改

**Comment by switefaster** [comment]
> > 谁接这个issue记得讲一声
> 
> 我这几天改
> 不对这是交互的部分
> 我没参与
> 还真得让 ck 改

ok

**Comment by switefaster** [comment]
@M1k0t0 你可改好了
